services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      DATABASE_HOSTNAME: postgres
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: Guitar0123
      DATABASE_NAME: fastapi
      DATABASE_USERNAME: postgres
      SECRET_KEY: 23165487
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 300
      # Corrected DATABASE_URL to use the 'postgres' service name instead of localhost
      DATABASE_URL: "postgresql://postgres:Guitar0123@postgres:5432/fastapi"

  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: Guitar0123
      POSTGRES_DB: ryze # Changed to match DATABASE_NAME
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
