name: Build and Deploy Code

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    environment:
      name: Testing
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Wait for PostgreSQL
        run: until pg_isready --host=localhost --port=5432; do sleep 2; done

      - name: Run tests
        run: pytest -v

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH and deploy to the Ubuntu server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          password: ${{ secrets.PROD_PASSWORD }}
          port: 22
          script: |
            cd /home/dane/app/src  # Adjust the path if needed
            git pull
            echo ${{ secrets.PROD_PASSWORD }} | sudo -S systemctl restart ryzeapi

      - name: Set production environment variables
        run: |
          export DATABASE_HOSTNAME="${{ secrets.DATABASE_HOSTNAME }}"
          export DATABASE_PORT="${{ secrets.DATABASE_PORT }}"
          export DATABASE_USERNAME="${{ secrets.DATABASE_USERNAME }}"
          export DATABASE_PASSWORD="${{ secrets.DATABASE_PASSWORD }}"
          export DATABASE_NAME="${{ secrets.DATABASE_NAME }}"
          export SECRET_KEY="${{ secrets.SECRET_KEY }}"
          export ALGORITHM="${{ secrets.ALGORITHM }}"
          export ACCESS_TOKEN_EXPIRE_MINUTES="${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}"
          echo "Environment variables set for production"

      - name: Restart the application service
        run: echo ${{ secrets.PROD_PASSWORD }} | sudo -S systemctl restart ryzeapi
