name: Build and Deploy Code

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python (if your deployment involves running Python commands)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      # Install dependencies (if needed, you can skip this if not relevant)
      - name: Install dependencies
        run: pip install -r requirements.txt

      # SSH into the Ubuntu server and deploy
      - name: SSH and deploy to the Ubuntu server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }} # Add PROD_HOST to your GitHub Secrets
          username: ${{ secrets.PROD_USERNAME }} # Add PROD_USERNAME to your GitHub Secrets
          password: ${{ secrets.PROD_PASSWORD }} # Add PROD_PASSWORD to your GitHub Secrets
          port: 22 # Adjust the port if needed (default is 22)
          script: |
            cd /home/dane/app/src  # Adjust the path to where your app is located
            git pull                # Pull the latest changes from the repository
            # Set environment variables on the Ubuntu server
            export DATABASE_HOSTNAME=${{ secrets.DATABASE_HOSTNAME }}            # Set your database hostname
            export DATABASE_PORT=${{ secrets.DATABASE_PORT }}                    # Set your database port
            export DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}            # Set your database username
            export DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}            # Set your database password
            export DATABASE_NAME=${{ secrets.DATABASE_NAME }}                    # Set your database name
            export SECRET_KEY=${{ secrets.SECRET_KEY }}                          # Set your secret key
            export ALGORITHM=${{ secrets.ALGORITHM }}                            # Set your algorithm for token
            export ACCESS_TOKEN_EXPIRE_MINUTES=${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}  # Set token expiration time
            # Restart the application service
            echo ${{ secrets.PROD_PASSWORD }} | sudo -S systemctl restart ryzeapi # Replace 'ryzeapi' with your service name
